// Generated by CoffeeScript 1.9.3
(function() {
  var prepareBounceInElements;

  $(document).ready(function() {
    prepareBounceInElements();
  });

  prepareBounceInElements = function() {
    var animatedElements;
    animatedElements = 'img.circular, a.flex-box, img#contact, div#contactButtonContainer';
    $(animatedElements).addClass('animated bounceIn');
    $(animatedElements).one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', (function() {
      $(this).removeClass('animated bounceIn');
    }));
  };

}).call(this);
